name: Static Analysis (Semgrep)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run Semgrep
        run: semgrep ci
        env:
          SEMGREP_RULES: "p/owasp-top-ten p/typescript p/javascript p/secrets"
